import {
  ArrangeMenuActions,
  ColorButtonsServiceActions,
  ControlFrameEffectsActions,
  EditMenuActions,
  EndpointButtonsServiceActions,
  FontControlsComponentActions,
  FontFamilyButtonServiceActions,
  FontSizeButtonServiceActions,
  InsertMenuActions,
  LineDashButtonServiceActions,
  LineWidthButtonServiceActions,
  MouseMachineActions,
  PageBackgroundContextMenuActions,
  PageViewportComponentActions,
  SelectionMenuActions,
  SketchbookViewComponentActions,
  TextOptionsServiceActions,
  ViewMenuActions,
} from '@tfx-diagram/diagram-data-access-store-actions';

export const undoableOperationTriggerActions: { [id: string]: boolean } = {
  [SketchbookViewComponentActions.addPageConfirmed.type]: true,
  [SketchbookViewComponentActions.pageTitleChange.type]: true,
  [SketchbookViewComponentActions.pageOrderChange.type]: true,
  [SketchbookViewComponentActions.deletePageClick.type]: true,
  [SketchbookViewComponentActions.currentPageChange.type]: true,
  [ViewMenuActions.pageAlignmentChange.type]: true,
  [ViewMenuActions.shapeSnapToggle.type]: true,
  [ViewMenuActions.showMousePositionToggle.type]: true,
  [ViewMenuActions.mousePositionCoordsTypeChange.type]: true,
  [ViewMenuActions.showGridToggle.type]: true,
  [ViewMenuActions.snapToGridToggle.type]: true,
  [ViewMenuActions.screenPixelDensityChange.type]: true,
  [ViewMenuActions.zoomChange.type]: true,
  [SketchbookViewComponentActions.zoomChange.type]: true,
  [InsertMenuActions.insertCircle.type]: true,
  [InsertMenuActions.insertRectangle.type]: true,
  [InsertMenuActions.insertArc.type]: true,
  [InsertMenuActions.insertCurve.type]: true,
  [InsertMenuActions.insertLine.type]: true,
  [InsertMenuActions.insertTriangle.type]: true,
  [PageBackgroundContextMenuActions.insertCircle.type]: true,
  [PageBackgroundContextMenuActions.insertRectangle.type]: true,
  [PageBackgroundContextMenuActions.insertArc.type]: true,
  [PageBackgroundContextMenuActions.insertCurve.type]: true,
  [PageBackgroundContextMenuActions.insertLine.type]: true,
  [PageBackgroundContextMenuActions.insertTriangle.type]: true,
  [PageBackgroundContextMenuActions.pasteClick.type]: true,
  [FontFamilyButtonServiceActions.fontPropsChange.type]: true,
  [FontControlsComponentActions.fontPropsChange.type]: true,
  [FontSizeButtonServiceActions.fontPropsChange.type]: true,
  [ColorButtonsServiceActions.fontPropsChange.type]: true,
  [TextOptionsServiceActions.fontPropsChange.type]: true,
  [ControlFrameEffectsActions.editTextChange.type]: true,
  [ColorButtonsServiceActions.fillColorChange.type]: true,
  [ColorButtonsServiceActions.lineColorChange.type]: true,
  [LineWidthButtonServiceActions.lineWidthChange.type]: true,
  [LineDashButtonServiceActions.lineDashChange.type]: true,
  [EndpointButtonsServiceActions.startEndpointChange.type]: true,
  [EndpointButtonsServiceActions.finishEndpointChange.type]: true,
  [MouseMachineActions.leftButtonDown.type]: true,
  [MouseMachineActions.ctrlLeftButtonDown.type]: true,
  [PageViewportComponentActions.rightButtonDown.type]: true,
  [SelectionMenuActions.selectAllClick.type]: true,
  [SelectionMenuActions.inverseSelectionClick.type]: true,
  [ArrangeMenuActions.bringToFrontClick.type]: true,
  [ArrangeMenuActions.sendToBackClick.type]: true,
  [ArrangeMenuActions.bringItemForward.type]: true,
  [ArrangeMenuActions.sendItemBackward.type]: true,
  [ArrangeMenuActions.groupClick.type]: true,
  [ArrangeMenuActions.ungroupClick.type]: true,
  [ArrangeMenuActions.alignObjectsClick.type]: true,
  [ArrangeMenuActions.distributeObjectsClick.type]: true,
  [ArrangeMenuActions.shapeResizeClick.type]: true,
  [EditMenuActions.deleteClick.type]: true,
  [EditMenuActions.pasteClick.type]: true,
  [ControlFrameEffectsActions.dragStartHandle.type]: true,
  [ControlFrameEffectsActions.dragStartSingleSelection.type]: true,
  [ControlFrameEffectsActions.dragStartMultiSelection.type]: true,
  [ControlFrameEffectsActions.dragStartSelectionBox.type]: true,
};
